# Generated by Django 5.1.2 on 2024-11-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BirthDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fav_color1',
        ),
    ]
