# Generated by Django 5.1.2 on 2024-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_user_birthdate_remove_user_agree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracModel',
            fields=[
                ('auto_filled', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('char_field', models.CharField(max_length=255)),
            ],
        ),
    ]
